spring:
  config:
    activate:
      on-profile: common

  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace