spring:
  profiles:
    active:
    group:
      LOCAL_1:
        - common
        - local
        - server-port-1

      LOCAL_2:
        - common
        - local
        - server-port-2

      SERVER_1:
        - common
        - prod
        - server-port-1

      SERVER_2:
        - common
        - prod
        - server-port-2