spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/doneit
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  #  address: 0.0.0.0
  port:

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace